### ISSUE TITLE
Support for Android

### ISSUE THREAD

**Issue by n-maiya** [momolarson/BLEServiceDiscovery#12]
Can't I run this directly on Android devices? 
When I run **npx react-native run-android** it says **error Unrecognized command "run-android".**

Is there anything I need to change?

**Comment by n-maiya** [comment]
> Can't I run this directly on Android devices?
> When I run **npx react-native run-android** it says **error Unrecognized command "run-android".**
> 
> Is there anything I need to change?

This can be closed. Missed **npm install --save react-native-ble-plx**

**Comment by momolarson** [comment]
@n-maiya - Thanks!!
