### ISSUE TITLE
Metro Bundler has encountered an error: Cannot read property 'transformFile' of undefined

### ISSUE THREAD

**Issue by manojrai84** [momolarson/BLEServiceDiscovery#4]
BLEDiscoveryApp[4528:1159133] TCP Conn 0x280f44c00 Failed 
![IMG_2C4EB746F198-1](https://user-images.githubusercontent.com/12627850/82051062-cc763000-96eb-11ea-848d-02c363d0bb1f.jpeg)

Please check what is the issue i am not able to run this code

**Comment by momolarson** [comment]
This not a code error, but a development environment error, are you developing for Android or iOS?
