### ISSUE TITLE
Page stuck in loding data page

### ISSUE THREAD

**Issue by Brahma-S-P** [momolarson/BLEServiceDiscovery#7]
As soon as I load the app. The app is stuck in the loading data page even though the nordic device is available.

**Comment by captDaylight** [comment]
Are you doing this in a simulator? I didn't see a list of peripherals until I fired the code up on my iphone.

**Comment by evialliresa** [comment]
Same with me, stuck in BLE list. When i debug it stuck on addBLE


![app](https://user-images.githubusercontent.com/24818242/94106716-335be080-fe66-11ea-95e8-88914e2975e0.jpeg)
<img width="549" alt="Screen Shot 2020-09-24 at 1 02 06 PM" src="https://user-images.githubusercontent.com/24818242/94106726-36ef6780-fe66-11ea-9f92-4a63bf2ab80a.png">

<img width="549" alt="code" src="https://user-images.githubusercontent.com/24818242/94106746-440c5680-fe66-11ea-8ac9-86be534358e4.png">

**Comment by momolarson** [comment]
are you using a simulator or running on device?

**Comment by Datagrdn** [comment]
I have the same problem when running on a Pixel 3a. Any insight here?

**Comment by momolarson** [comment]
Hello, 

I have been looking into this, and it appears this has something to do with the name field in the device object being set to null.  As @evialliresa pointed out, the app is "stuck" at the addBLE dispatch because the device has no name.  You can check this in the reducer : 

https://github.com/momolarson/BLEServiceDiscovery/blob/09f6c6635eda63500e67b45db8d31ad8179964f6/reducers/BLEReducer.js#L16

I am assuming you know how to debug a react app and set up break points??  That would be the preferred way to see if your app is returning devices, and what the device object looks like.

**Comment by momolarson** [comment]
Also, this is probably a permissions issue as well, even though there are permissions in the manifest, you are not being presented the modal to accept them.

**Comment by momolarson** [comment]
I have made some changes to the code that should help with this.  I've updated the Android Manifests for bluetooth permissions, and added code to prompt the user after installing the app.  I've also removed the check to see if a device is connectable from the action that stops it from being added to the device list, and moved that into a UI change.  Now all devices will appear if they have a name, and the devices will be styled differently depending on if you can connect.

**Comment by R2boot3r** [comment]
Hello momolarson, 

I have been trying to use your BLEServiceDiscovery app but as others i have been stuck on the loading data part. I am using the last version commited on a Xiaomi mi 9t pro . I have in addition not been prompted to authorise bluetooth permission by the app.
The Nodejs server doesn't provide any logs that could be useful and same while building the app.

I'm learning react native for a school projet and I will try to implement break point for debugging.

Thank you for your time!
